version: '3'
services:
  redis:
    image: redis:7.2
    restart: always
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file: .env
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis-data:/data
  news-bot-app:
    build:
      context: .
    restart: always
    env_file: .env
    environment:
      - TZ=Europe/Moscow
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - logs:/app/logs
volumes:
  redis-data:
  logs: